#!/bin/sh

if [ $(pactl get-sink-mute @DEFAULT_SINK@ | grep -oP 'Mute:\s*\K\w+') == "yes" ]; then
    echo 0
    exit
else
    volume_output=$(pactl get-sink-volume @DEFAULT_SINK@  | grep -oP '\d+%' | head -n1)
    echo ${volume_output%%%}
    exit
fi