#!/usr/bin/env bash

# get search-res-path: <path>
item=$(eww state | grep search-res-path | cut -d' ' -f2)

# Check if the file exists
if [[ ! -f "$item" ]]; then
    eww update search-res-name="file not found: $item"
    exit 1
fi

# Extract the base name of the .desktop file (i.e., the application name)
app_name=$(basename "$item" .desktop)

# Use gtk-launch to launch the application by its base name (without the .desktop extension)
gtk-launch "$app_name" &

# Clear the content of the file
eww update search-res-name="" search-res-path="" launch-val=""

# Close the launcher
bash ~/.config/eww/scripts/toggle_center 2