#!/usr/bin/env bash

# Temporary file to store the result
output_file="$(realpath ~/.config/eww/scripts)/launcher_output.txt"
touch "$output_file"
input="$@"  # The input from the user

if [[ -z $input ]]; then
    eww update search-res-name=""
    exit 0
fi

# Check if command starts with "=" (for equation calculations)
if [[ $input == "="* ]]; then
    # Check for qalc
    if ! command -v qalc &> /dev/null; then
        eww update search-res-name="qalc not found"
        exit 1
    fi

    # Calculate the equation
    eww update search-res-name="$(qalc "${input:1}")"
    exit 0
fi

# get directories to search for .desktop files
desktop_directories=(
    "/usr/share/applications"        # System-wide applications
    "~/.local/share/applications"    # User-specific applications
    "/usr/local/share/applications"  # Local installations
    "/opt"                           # Optional, some apps are installed here
)

# build a list of all .desktop files from the specified directories
desktop_files=()

for dir in "${desktop_directories[@]}"; do
    # expand the tilde to the user's home directory
    dir=$(eval echo "$dir")

    # check if the directory exists
    if [[ -d $dir ]]; then
        # append all .desktop files to the list
        desktop_files+=("$dir"/*.desktop)
    fi
done

# fuzzy search for the input in the .desktop Name and Exec fields, to print the result
for file in "${desktop_files[@]}"; do
    # get the Name and Exec fields from the .desktop file
    name=$(grep -m 1 -oP "(?<=Name=).*" "$file" 2>/dev/null)
    exec=$(grep -m 1 -oP "(?<=Exec=).*" "$file" 2>/dev/null)

    # if name not in input and exec not in input (grep, case insensitive), skip
    if ! (echo "$name" | grep -i "$input" &>/dev/null) && ! (echo "$exec" | grep -i "$input" &>/dev/null); then
        continue
    fi

    # print the name and exec to the output file
    eww update search-res-name="$name" search-res-path="$file"
    return 0
done

# if no match was found, print an error message
eww update search-res-name="No match found"
exit 1