#!/usr/bin/env bash

# first arg is index
index=$1

state=$(eww state | grep center_selected | cut -d' ' -f2)

# if state == index, set state to 0
if [ "$state" == "$index" ]; then
    eww update "center_selected=0"
else
    eww update "center_selected=$index"
fi