#!/usr/bin/env bash

if [[ $(eww active-windows) == *"bar"* ]]; then
    eww close bar
    eww open launcher
else
    if [[ $(eww active-windows) == *"launcher"* ]]; then
        eww close launcher
        eww open bar
    fi
fi